UserApp/urls.py
from django.conf.urls import url

from UserApp import views

urlpatterns=[
    url(r'^register/',views.register,name='register'),
    url(r'^checkName/',views.checkName,name='checkName'),
#     激活
    url(r'^account/',views.account),
#     登录
    url(r'^login/',views.login,name='login'),
#     验证码
    url(r'^get_code/',views.get_code),

#     退出
    url(r'^logout/',views.logout,name='logout'),


#     发送邮件
    url(r'^testEmail/',views.testEmail),


]

axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axfhome/',include('HomeApp.urls',namespace='axfhome')),
    url(r'^axfmarket/',include('MarketApp.urls',namespace='axfmarket')),
    url(r'^axfcart/',include('CartApp.urls',namespace='axfcart')),
    url(r'^axfmine/',include('MineApp.urls',namespace='axfmine')),
    url(r'^axfuser/',include('UserApp.urls',namespace='axfuser')),
    url(r'^axforder/',include('OrderApp.urls',namespace='axforder'))
]

templates/axf/main/mine/mine.html
{% extends 'base_main.html' %}


{% load static %}

{% block title %}
    {{ block.super }}
    我的
{% endblock %}


{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/main/mine/css/mine.css' %}">
{% endblock %}


{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'axf/main/mine/js/mine.js' %}"></script>
{% endblock %}


{% block content %}
    {{ block.super }}

    <div id="mine">
        <div class="fixed">

            {% if user_id %}
                 <span>
                    <img src="/static/upload/{{ user.u_icon }}" alt="">
                </span>
                {% else %}

                     <span class="glyphicon glyphicon-user"></span>
            {% endif %}



            {% if user_id %}
                <p>{{ user.u_name }}</p>
                {% else %}
                <p id="nologin">未登录</p>
            {% endif %}

            <p>
                <span class="glyphicon glyphicon-fire"></span>
                <span>等级</span>
            </p>

            <p>
                <span class="glyphicon glyphicon-heart"></span>
                商品收藏
            </p>
        </div>

        <div id="regis">注册</div>

        <div class="mine">
            <p>
                <span>全部订单</span>
                <a href="">全部订单》</a>
            </p>

            <div id="nav">
                <ul>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-usd"></span>
                            </dt>
                            <dd>待付款</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-envelope"></span>
                            </dt>
                            <dd>待收货</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-pencil"></span>
                            </dt>
                            <dd>待评价</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-retweet"></span>
                            </dt>
                            <dd>退款/售后</dd>
                        </dl>
                    </li>
                </ul>
            </div>

            <menu>
                <ul>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-bullhorn"></span>
                            </dt>
                            <dd>积分商城</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-credit-card"></span>
                            </dt>
                            <dd>优惠券</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-import"></span>
                            </dt>
                            <dd>收货地址</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-phone-alt"></span>
                            </dt>
                            <dd>客服反馈</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-asterisk"></span>
                            </dt>
                            <dd>关于我们</dd>
                        </dl>
                    </li>
                </ul>
            </menu>


            {% if user_id %}
                <p>
                    <a href="{% url 'axfuser:logout' %}">退出</a>
                </p>
            {% endif %}

            
        </div>

    </div>

{% endblock %}