CartApp/urls.py
from django.conf.urls import url

from CartApp import views

urlpatterns=[
    url(r'^cart/',views.cart,name='cart'),
#     添加到购物车
    url(r'^addToCart/',views.addToCart),

#     减少数据量
    url(r'^subCart/',views.subCart),

#     改变选中状态
    url(r'^changeStatus/',views.changeStatus),

#     全选
    url(r'^allSelect/',views.allSelect),
]

HomeApp/urls.py
from django.conf.urls import url

from HomeApp import views

urlpatterns=[
    url(r'^home/',views.home,name='home'),
]

MarketApp/urls.py
from django.conf.urls import url

from MarketApp import views

urlpatterns=[
    url(r'^market/',views.market,name='market')
]

MineApp/urls.py
from django.conf.urls import url

from MineApp import views

urlpatterns=[
    url(r'^mine/',views.mine,name='mine'),
]

axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axfhome/',include('HomeApp.urls',namespace='axfhome')),
    url(r'^axfmarket/',include('MarketApp.urls',namespace='axfmarket')),
    url(r'^axfcart/',include('CartApp.urls',namespace='axfcart')),
    url(r'^axfmine/',include('MineApp.urls',namespace='axfmine')),
    url(r'^axfuser/',include('UserApp.urls',namespace='axfuser')),
    url(r'^axforder/',include('OrderApp.urls',namespace='axforder'))
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>
        {% block title %}
        
        {% endblock %}
    </title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">

    {% block ext_css %}
    
    {% endblock %}

</head>
<body>

    {% block header %}
    
    {% endblock %}

    {% block content %}
    
    {% endblock %}


    {% block footer %}
    
    {% endblock %}


    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/base.js' %}"></script>

    {% block ext_js %}
    
    {% endblock %}

</body>
</html>

templates/base_main.html
{% extends 'base.html' %}

{% load static %}


{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/main/css/main.css' %}">
{% endblock %}


{% block header %}
    {{ block.super }}
    <header></header>
{% endblock %}




{% block footer %}
    {{ block.super }}

    <footer>
        <a href="{% url 'axfhome:home' %}" class="home">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>首页</dd>
            </dl>
        </a>
        <a href="{% url 'axfmarket:market' %}" class="market">
                <dl>
                    <dt>
                        <span></span>
                    </dt>
                    <dd>闪购</dd>
                </dl>
        </a>
        <a href="{% url 'axfcart:cart' %}" class="cart">
                <dl>
                    <dt>
                        <span></span>
                    </dt>
                    <dd>购物车</dd>
                </dl>
        </a>
        <a href="{% url 'axfmine:mine' %}" class="mine">
                <dl>
                    <dt>
                        <span></span>
                    </dt>
                    <dd>我的</dd>
                </dl>
        </a>
    </footer>
    
{% endblock %}

templates/base_order.html
{% extends 'base.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/order/css/order.css' %}">
{% endblock %}


{% block header %}
    {{ block.super }}
    <header></header>
{% endblock %}

templates/base_user.html
{% extends 'base.html' %}

{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/user/css/user.css' %}">
{% endblock %}


{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'axf/user/js/md5.js' %}"></script>
{% endblock %}



{% block header %}
    {{ block.super }}
    <header></header>
{% endblock %}