axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axfhome/',include('HomeApp.urls',namespace='axfhome')),
    url(r'^axfmarket/',include('MarketApp.urls',namespace='axfmarket')),
    url(r'^axfcart/',include('CartApp.urls',namespace='axfcart')),
    url(r'^axfmine/',include('MineApp.urls',namespace='axfmine')),
    url(r'^axfuser/',include('UserApp.urls',namespace='axfuser')),
    url(r'^axforder/',include('OrderApp.urls',namespace='axforder'))
]

OrderApp/models.py
from django.db import models

# Create your models here.
from MarketApp.models import AxfGoods
from UserApp.models import AxfUser


class AxfOrder(models.Model):
    o_user = models.ForeignKey(AxfUser)
    o_price = models.FloatField()

    class Meta:
        db_table = 'axf_order'


class AxfOrderGoods(models.Model):
    aog_order = models.ForeignKey(AxfOrder)
    aog_goods = models.ForeignKey(AxfGoods)

    aog_num = models.IntegerField(default=1)


    class Meta:
        db_table = 'axf_ordergoods'

templates/axf/order/order_detail.html
{% extends 'base_order.html' %}



{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/order/css/order_detail.css' %}">
{% endblock %}


{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'axf/order/js/order_detail.js' %}"></script>
{% endblock %}


{% block title %}
    {{ block.super }}
    订单详情
{% endblock %}


{% block content %}
    {{ block.super }}


    <div class="container">
    订单编号:{{ order.id }}
    {% for axfordergoods in order.axfordergoods_set.all %}
        <div class="menuList">


                    <a href="">
                        <img src="/static{{ axfordergoods.aog_goods.productimg }}" alt="">
                        <p>{{ axfordergoods.aog_goods.productlongname }}</p>
                        <p class="presentPrice">{{ axfordergoods.aog_goods.price }}</p>
                    </a>




                <section>
                    <span>{{ axfordergoods.aog_num }}</span>
                </section>
        </div>
    {% endfor %}

        <p class="total_price">总价:<span id="total_price">{{ order.o_price }}</span></p>

        <button class="btn-block btn-success" id="pay">支付</button>

    </div>
{% endblock %}