UserApp/urls.py
from django.conf.urls import url

from UserApp import views

urlpatterns=[
    url(r'^register/',views.register,name='register'),
    url(r'^checkName/',views.checkName,name='checkName'),
#     激活
    url(r'^account/',views.account),
#     登录
    url(r'^login/',views.login,name='login'),
#     验证码
    url(r'^get_code/',views.get_code),

#     退出
    url(r'^logout/',views.logout,name='logout'),


#     发送邮件
    url(r'^testEmail/',views.testEmail),


]

axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axfhome/',include('HomeApp.urls',namespace='axfhome')),
    url(r'^axfmarket/',include('MarketApp.urls',namespace='axfmarket')),
    url(r'^axfcart/',include('CartApp.urls',namespace='axfcart')),
    url(r'^axfmine/',include('MineApp.urls',namespace='axfmine')),
    url(r'^axfuser/',include('UserApp.urls',namespace='axfuser')),
    url(r'^axforder/',include('OrderApp.urls',namespace='axforder'))
]

templates/axf/user/active.html
<h3>尊敬的澡王<span style="color: orange;">{{ name }}</span>您好:</h3><br>
       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;欢迎光临红浪漫高级洗浴,鉴于之前的洗澡信誉良好,点击以下链接可以领取优惠卷,<a href="{{ url }}">__点我__</a><br>


       &nbsp;&nbsp;&nbsp;&nbsp;如果点击链接未遂,请将{{ url }}复制到浏览器上。<br>

        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;祝您洗澡愉快！！！

templates/axf/user/login.html
{% extends 'base_user.html' %}

{% load static %}


{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'axf/user/js/login.js' %}"></script>
{% endblock %}



{% block content %}
    {{ block.super }}

    <span style="color: red">{{ msg }}</span>
    <form action="{% url 'axfuser:login' %}" method="post" onsubmit="return parse();">
        {% csrf_token %}
        <div class="container">
            <div class="form-group">
                <label for="exampleInputName">用户名字</label>
                <input type="text" name='name' class="form-control" id="exampleInputName" placeholder="3到6个英文字母">
                <span id="nameinfo"></span>
            </div>

            <div class="form-group">
                <label for="exampleInputPassword1">密码</label>
                <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="请输入密码">
            </div>

            <img src="/axfuser/get_code/" id="icode" alt="" onclick="changeCode();">


            <input type="text" name="imgcode">


            <button type="submit" class="btn btn-default btn-block btn-success">登录</button>

        </div>
    </form>
{% endblock %}

templates/axf/user/register.html
{% extends 'base_user.html' %}


{% load static %}

{% block title %}
    {{ block.super }}
    注册
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'axf/user/js/register.js' %}"></script>
{% endblock %}



{% block content %}
    {{ block.super }}

    <form action="{% url 'axfuser:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container">
            <div class="form-group">
                <label for="exampleInputName">用户名字</label>
                <input type="text" name='name' class="form-control" id="exampleInputName" placeholder="3到6个英文字母">
                <span id="nameinfo"></span>
            </div>

            <div class="form-group">
                <label for="exampleInputPassword1">密码</label>
                <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="请输入密码">
            </div>

            <div class="form-group">
                <label for="exampleInputPassword2">再次输入密码</label>
                <input type="password" class="form-control" id="exampleInputPassword2" placeholder="请再次输入密码">
                <span id="passwordinfo"></span>
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">邮箱</label>
                <input type="email" name="email" class="form-control" id="exampleInputEmail1" placeholder="请输入邮箱地址">
            </div>

            <div class="form-group">
                <label for="exampleInputFile">头像</label>
                <input type="file" name="icon" id="exampleInputFile">
            </div>

            <button type="submit" class="btn btn-default btn-block btn-success">注册</button>
        </div>
    </form>


{% endblock %}